FROM node:22.17.1-alpine

# Install compilers and runtime environments
RUN apk add --no-cache python3 g++ build-base

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

CMD ["sh", "-c", "node seed.js && npm run dev"]